convert Base\moon.tga Base\moon.png
convert Base\moonEMSS.tga Base\moonEMSS.png
convert Buildings\buildingtex.tga Buildings\buildingtex.png
convert Buildings\buildingtexEMS.tga Buildings\buildingtexEMS.png
convert Buildings\gravel.tga Buildings\gravel.png
convert Buildings\indust.tga Buildings\indust.png
convert Buildings\industEMS.tga Buildings\industEMS.png
convert Buildings\rail2.tga Buildings\rail2.png
convert Buildings\windsock.tga Buildings\windsock.png
convert Fence\fence.tga Fence\fence.png
convert Palms\groundcover.tga Palms\groundcover.png
convert Palms\groundcover2.tga Palms\groundcover2.png
convert Palms\groundcoverNRM.tga Palms\groundcoverNRM.png
convert Palms\palm_tree_PNG2505.tga Palms\palm_tree_PNG2505.png
